name: build project
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  build:
    using: 'docker'
    image: 'Dockerfile'
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: npx playwright test


