name: build and push image
'on':
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build-push-action
        uses: docker/build-push-action@v5
        with:
          push: true
          tag: 'docker.io/osachi/arkadium:latest'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

