name: build and push image

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      context: .
      push: true
      tags: "ghcr.io/osachi/arkadium:latest"
      cache-from: type=gha
      cache-to: type=gha,mode=max
